[package]
name = "slop-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "slop"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
slop-asset = { workspace = true }
slop-core = { workspace = true, features = ["subscriber"] }

[lints]
workspace = true
