[package]
name = "example-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "example-model"
path = "src/main.rs"

[dependencies]
slop-app = { workspace = true }
slop-asset = { workspace = true }
slop-core = { workspace = true, features = ["subscriber"] }
slop-ecs = { workspace = true }
slop-math = { workspace = true }
slop-reflect = { workspace = true }
slop-render = { workspace = true }
slop-rhi = { workspace = true }

[lints]
workspace = true
