[package]
name = "slop-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
egui = { workspace = true }
slop-asset = { workspace = true }
slop-core = { workspace = true }
slop-rhi = { workspace = true }

thiserror = { workspace = true }

[lints]
workspace = true
